### ISSUE TITLE
Not an Issue but thanks

### ISSUE THREAD

**Issue by MacsInSpace** [Digressive/MDT-Setup#1]
Hey thanks for putting a great script out there.
I'll be taking and heavily modifying it for my/our junior techs and removing  a lot of interaction in preference of defaults so dont want to make a pull request. but wanted to share an add-on you may appreciate or want to roll back into your main.

I've scripted the scraping and downloading of (always) the latest MDT, ADKWinPE, and ADK.

(Please forgive it.. it's "just working" without a whole lot of checking yet. But it's working!👍)

https://github.com/MacsInSpace/MDT-Setup/blob/main/GetMDT.ps1

Thanks again.

**Comment by MacsInSpace** [comment]
Don't* sorry. Mobile and can't edit (?)

**Comment by kieranwalsh** [comment]
Nice addition - thank you.
